### ISSUE TITLE
Unrecognised app

### ISSUE THREAD

**Issue by MickeyDaMuller** [baranyildirim/google_pay#1]
So have searched all through the whole internet to see if I can get any code to help with google pay integration for flutter to replace my existing Java android code but the closet was https://pub.dev/packages/google_pay which loads Google play UI but payment not successful as it shows an error that Unrecognised app.

**Comment by ninjaasmoke** [comment]
Probably because you are trying the 'test' environment and not 'production'.
Do check and tell.

**Comment by MickeyDaMuller** [comment]
how can I check if it is in test or production? Also, how can I change from test to production?

**Comment by ninjaasmoke** [comment]
@MickeyDaMuller 

https://github.com/baranyildirim/google_pay/blob/7d132bce2c8548a8dace23d1ddb95f3074aa550f/example/lib/main.dart#L34

Like 34. I'm new to flutter and all, just reading and I found this

**Comment by baranyildirim** [comment]
You need to use your own Google Pay token. The example one will not work.

**Comment by ninjaasmoke** [comment]
@baranyildirim how to get that token?

**Comment by baranyildirim** [comment]
@ninjaasmoke This library uses Stripe for payments. I am currently working on supporting both Stripe and Square.
For stripe: https://stripe.com/docs/keys
